# Created using wingetcreate 1.1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.2.0.schema.json

PackageIdentifier: IDA.Pike
PackageVersion: 8.0.1738
PackageLocale: en-US
Publisher: IDA
PublisherUrl: https://pike.lysator.liu.se/
PackageName: Pike
PackageUrl: https://pike.lysator.liu.se/download/
License: MPL
ShortDescription: Pike programming language
ManifestType: defaultLocale
ManifestVersion: 1.2.0

